[theme]
background = "#103c48"
primary = "#adbcbc"
secondary = "#72898f"
title = "#41c7b9"
playing = "#75b938"
playing_bg = "#103c48"
playing_selected = "#84c747"
highlight = "#103c48"
highlight_bg = "#4695f7"
highlight_inactive_bg = "#2d5b69"
error = "#fa5750"
error_bg = "#103c48"
statusbar = "#adbcbc"
statusbar_bg = "#184956"
statusbar_progress = "#41c7b9"
statusbar_progress_bg = "#2d5b69"
cmdline = "#adbcbc"
cmdline_bg = "#103c48"
search_match = "#fa5750"
