[main]
font=JetBrainsMono Nerd Font Mono:size=12:weight=semibold
anchor=center
width=46
lines=16
inner-pad=14
vertical-pad=20
icon-theme=breeze-dark
terminal=footclient
prompt="  > "

[colors]
background=282c34ff
text=abb2bfff
# One Dark blue
match=61afefff
selection=3e4451ff
selection-text=abb2bfff
selection-match=61afefff
# Same gray niri uses for window borders
border=3a3a3aff
counter=5c6370ff

[border]
width=1
radius=14
